# backend/scraper/cities.py

CITIES = [
    # ── Capitales departamentales (32) ──────────────────────────────────
    {"name": "Bogotá",                  "department": "Cundinamarca"},
    {"name": "Medellín",                "department": "Antioquia"},
    {"name": "Cali",                    "department": "Valle del Cauca"},
    {"name": "Barranquilla",            "department": "Atlántico"},
    {"name": "Cartagena",               "department": "Bolívar"},
    {"name": "Cúcuta",                  "department": "Norte de Santander"},
    {"name": "Bucaramanga",             "department": "Santander"},
    {"name": "Pereira",                 "department": "Risaralda"},
    {"name": "Santa Marta",             "department": "Magdalena"},
    {"name": "Ibagué",                  "department": "Tolima"},
    {"name": "Manizales",               "department": "Caldas"},
    {"name": "Pasto",                   "department": "Nariño"},
    {"name": "Neiva",                   "department": "Huila"},
    {"name": "Villavicencio",           "department": "Meta"},
    {"name": "Armenia",                 "department": "Quindío"},
    {"name": "Valledupar",              "department": "Cesar"},
    {"name": "Montería",                "department": "Córdoba"},
    {"name": "Sincelejo",               "department": "Sucre"},
    {"name": "Popayán",                 "department": "Cauca"},
    {"name": "Florencia",               "department": "Caquetá"},
    {"name": "Quibdó",                  "department": "Chocó"},
    {"name": "Tunja",                   "department": "Boyacá"},
    {"name": "Riohacha",                "department": "La Guajira"},
    {"name": "San Andrés",              "department": "San Andrés y Providencia"},
    {"name": "Yopal",                   "department": "Casanare"},
    {"name": "Mocoa",                   "department": "Putumayo"},
    {"name": "Inírida",                 "department": "Guainía"},
    {"name": "Mitú",                    "department": "Vaupés"},
    {"name": "Puerto Carreño",          "department": "Vichada"},
    {"name": "San José del Guaviare",   "department": "Guaviare"},
    {"name": "Leticia",                 "department": "Amazonas"},
    {"name": "Arauca",                  "department": "Arauca"},
    # ── Ciudades intermedias importantes ────────────────────────────────
    {"name": "Palmira",                 "department": "Valle del Cauca"},
    {"name": "Buenaventura",            "department": "Valle del Cauca"},
    {"name": "Bello",                   "department": "Antioquia"},
    {"name": "Envigado",                "department": "Antioquia"},
    {"name": "Rionegro",                "department": "Antioquia"},
    {"name": "Soledad",                 "department": "Atlántico"},
    {"name": "Soacha",                  "department": "Cundinamarca"},
    {"name": "Girardot",                "department": "Cundinamarca"},
    {"name": "Dosquebradas",            "department": "Risaralda"},
    {"name": "Tuluá",                   "department": "Valle del Cauca"},
    {"name": "Floridablanca",           "department": "Santander"},
    {"name": "Barrancabermeja",         "department": "Santander"},
    {"name": "Sogamoso",                "department": "Boyacá"},
    {"name": "Duitama",                 "department": "Boyacá"},
    {"name": "Espinal",                 "department": "Tolima"},
    {"name": "Maicao",                  "department": "La Guajira"},
    {"name": "Magangué",                "department": "Bolívar"},
    {"name": "Lorica",                  "department": "Córdoba"},
    # ── Pueblos Patrimonio de Colombia ──────────────────────────────────
    {"name": "Mompox",                  "department": "Bolívar"},
    {"name": "Villa de Leyva",          "department": "Boyacá"},
    {"name": "Barichara",               "department": "Santander"},
    {"name": "Salento",                 "department": "Quindío"},
    {"name": "Guaduas",                 "department": "Cundinamarca"},
    {"name": "Honda",                   "department": "Tolima"},
    {"name": "Jardín",                  "department": "Antioquia"},
    {"name": "Jericó",                  "department": "Antioquia"},
    {"name": "Concepción",              "department": "Antioquia"},
    {"name": "Támesis",                 "department": "Antioquia"},
    {"name": "Aguadas",                 "department": "Caldas"},
    {"name": "Salamina",                "department": "Caldas"},
    {"name": "Neira",                   "department": "Caldas"},
    {"name": "Filadelfia",              "department": "Caldas"},
    {"name": "Marsella",                "department": "Risaralda"},
    {"name": "Filandia",                "department": "Quindío"},
    {"name": "Ráquira",                 "department": "Boyacá"},
    {"name": "Monguí",                  "department": "Boyacá"},
    {"name": "Tibasosa",                "department": "Boyacá"},
    {"name": "Sutamarchán",             "department": "Boyacá"},
    {"name": "Vélez",                   "department": "Santander"},
    {"name": "Playa de Belén",          "department": "Norte de Santander"},
    {"name": "San Agustín",             "department": "Huila"},
    {"name": "La Plata",                "department": "Huila"},
    {"name": "Isnos",                   "department": "Huila"},
    {"name": "Ciénaga",                 "department": "Magdalena"},
    {"name": "El Banco",                "department": "Magdalena"},
    {"name": "Manaure",                 "department": "La Guajira"},
    {"name": "Providencia",             "department": "San Andrés y Providencia"},
    {"name": "Bahía Solano",            "department": "Chocó"},
    {"name": "Nuquí",                   "department": "Chocó"},
]
